ebu/ear-production-suite

.github/workflows/build.yml

set-env and add-path: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Avoid deprecated GitHub Actions commands

---

ear-production-suite/plugins/scene/src/nng_wrappers.h

Break if nng aio result is ECLOSED to avoid hitting assertion when Reaper is closed (macOS)

Avoid hitting assertion on Reaper close

---

reaper-adm-extension/src/reaper_adm/exportaction_admsource-earvst.cpp
reaper-adm-extension/src/reaper_adm/exportaction_admsource-earvst.h

Attempts to fix issue #16 .
Implements new function to check whether envelopes are bypassed and introduces new if-case to check for that.

Ial issue 16 bypassed automation

---

reaper-adm-extension/src/reaper_adm/exportaction_parameterprocessing.cpp

Using chrono objects for all arithmetics fixes the issue - python renderer gives no warnings anymore.

Ial issue 47 block time rounding

---

ear-production-suite/lib/src/scene_backend.cpp

If this doesn't fix the actual issue, it will at least fix a crash that happened every time i opened a project with monitoring plugins (GUI closed) but without scene, and then added the scene.

Reset rebuildSceneStore flag to avoid rebuilding in every audio callback

---

reaper-adm-extension/src/reaper_adm/exportaction_parameterprocessing.cpp

As discussed to fix #44, for blocks with zero-duration a JumpPosition flag should be set. If there are multiple points at the same timestamp, the current implementation always creates 2 blocks, where the second block has zero-duration and by using the already existing flags, a JumpPosition for this block can be set.

#44 Export - use JumpPosition

---

ear-production-suite/plugins/direct_speakers/CMakeLists.txt
ear-production-suite/plugins/monitoring/CMakeLists.txt
ear-production-suite/plugins/object/CMakeLists.txt
ear-production-suite/plugins/scene/CMakeLists.txt
reaper_adm_stem_plugin/src/CMakeLists.txt

A typo in a cmake variable prevented default install locations from being correctly set for all plugins, this fixes that.

Fix install path regression introduced by #50

---

ear-production-suite/plugins/scene/src/object_view.hpp
ear-production-suite/plugins/shared/components/look_and_feel/colours.hpp

Button now has a different color when interactivity is enabled. Since the suggested yellow didn't work great with the white text, i went for a darker orange instead. Colour needs to be adjusted later in colours.hpp.
Fixes #37

#37 Highlight Settings Button

---

reaper-adm-extension/src/reaper_adm/pluginsuite_ear.cpp

#89 introduced a bug where importing ADM files with directspeaker packs could result in DirectSpeaker plugins with layout set incorrectly. This fixes that problem.

update pluginsuite to correctly import new directspeaker packs

---

README.md
reaper-adm-extension/src/reaper_adm/menu.cpp
reaper-adm-extension/src/reaper_adm/menu.h
reaper-adm-extension/src/reaper_adm/pluginmain.cpp
reaper-adm-extension/src/reaper_adm/reaperapi.h
reaper-adm-extension/src/reaper_adm/reaperapiimpl.cpp
reaper-adm-extension/src/reaper_adm/reaperapiimpl.h
reaper-adm-extension/test/reaper_adm/mocks/reaperapi.h

Replaces #65
fixes #25 
As #65 but with refactor to reduce the amount of windows specific code

#25 language pack crashes

---

.github/workflows/build.yml

#98 Updated CI to be a bit less enthusiastic, but accidentally disabled building after a PR merge. This should fix that with a little luck.

CI: Build on push to main

---

ear-production-suite/plugins/scene/CMakeLists.txt
ear-production-suite/plugins/scene/src/element_view.cpp
ear-production-suite/plugins/scene/src/element_view.hpp
ear-production-suite/plugins/scene/src/element_view_list.cpp
ear-production-suite/plugins/scene/src/element_view_list.hpp
ear-production-suite/plugins/scene/src/elements_container.cpp
ear-production-suite/plugins/scene/src/elements_container.hpp
ear-production-suite/plugins/scene/src/scene_frontend_connector.cpp
ear-production-suite/plugins/scene/src/scene_frontend_connector.hpp

Closes #87 
`ElementViewList` maintained a `std::vector<ElementView*> elements_;`, and `ElementsContainer` also maintained a `std::vector<std::shared_ptr<ElementView>> elements;` - these could get out of sync, and hence why the UI appeared to be deleting the wrong item.
The easy fix would have been to modify the `JuceSceneFrontendConnector::elementMoved` method to ensure it updates the ordering of vector elements in the `ElementViewList` (which it already did) **AND** the vector of elements in `ElementsContainer` such that the indices always matched and operations were always enacted on the correct vector elements.
However, it seemed redundant to me to be maintaining two vectors. It seems much more logical to just use the vector in `ElementsContainer`, and all operations concerning …

Fix #87 Scene appears to delete wrong item

---

reaper-adm-extension/src/reaper_adm/exportaction_admsource-earvst.h

This fixes a regression after the DirectSpeakers plugin was updated to support
more channel layouts. The max value of paramSpeakerLayout had not been updated
to reflect the new layout count. As the comment above the changed code suggests, we should consolidate
this stuff in one place, but leaving that for now as this is an urgent fix.

Fix export channel check for updated DirectSpeakers plugin

---

ear-production-suite-plugins/plugins/monitoring/src/monitoring_plugin_processor.cpp

First crash caused by using ear::getLayout during constructor, which throws because the lookup fails.
Second crash was a ear::internal_error "collinear points in convex hull" due to wrong channels pulled from 9_10_3 setup

2+7+0 Crash fix

---

CMakePresets.json

We're running out of space on the GitHub runners when building all the
plugins and generating pdb files, so just build the stereo monitoring
plugin which should cover most cases this build type is used for.

Build minimal plugin set on win RelWithDebInfo CI

---

ear-production-suite-plugins/plugins/scene/src/object_view.hpp

onStateChange fires on any state change, inc mouse enter/exit. onClick only fires if actually clicked or toggled with keyboard
Closes #85

Fix 85 - Use onClick rather than onStateChange

---

ear-production-suite-plugins/lib/CMakeLists.txt
ear-production-suite-plugins/lib/include/routing_overlap.hpp
ear-production-suite-plugins/lib/include/scene_backend.hpp
ear-production-suite-plugins/lib/src/routing_overlap.cpp
ear-production-suite-plugins/lib/src/scene_backend.cpp

fixes #141
The input plugins now properly flag whether metadata is changed. Updates to rendering / output gains only occur when metadata changes. In addition, the rendering plugin expects only one input per channel when calculating gains.
Routing clashes introduce a dependency between inputs, if A and B clash, and A is changed to resolve the clash, B is also affected as it needs it's gain recalculating. The renderer doesn't 'know' as B's metadata has not changed.
When there are overlapping inputs, rendering is incorrect (expected), however when this is resolved, only one of the inputs involved in the clash will be marked as changed (the one whose routing was altered) so the other can continue to be rendered incorrectly.
This fix keeps track of clashes in the Scene plugin. It causes all …

Set InputItemMetadata changed when routings clash or are resolved

---

reaper-adm-extension/src/reaper_adm/pluginregistry.cpp

The extension disables importing from a plugin suite with missing plugins, but
it was only searching for plugins via reaper-vstplugins64.ini. arm64 plugins are catalogued
in reaper-vstplugins_arm64.ini so were never found. This commit modifies the behaviour to search
both files.
Also prevents a warning about a missing ini file being shown when REAPER is launched in debug mode.

Search for arm64 plugins during init as well as x86_64

---

reaper-adm-extension/src/reaper_adm/admextraction.cpp
reaper-adm-extension/src/reaper_adm/admextraction.h
reaper-adm-extension/src/reaper_adm/automationenvelope.cpp
reaper-adm-extension/src/reaper_adm/automationpoint.cpp
reaper-adm-extension/src/reaper_adm/automationpoint.h
reaper-adm-extension/src/reaper_adm/parameter.cpp
reaper-adm-extension/src/reaper_adm/parametervaluemapping.cpp
reaper-adm-extension/test/reaper_adm/CMakeLists.txt

Because effective time is adding of 2 floats which can introduce precision error, it can be that the effective time of the previous block if AFTER the start time of the block you're processing. ~~This fix shifts start times according to the previous effective time to retain correct ordering. We're really only interested in effective time when placing points anyway - although those would be subject to precision error too!~~
~~This is the easiest fix. The best fix would be to use the adm::Time class throughout the entire code base, but that's huge work!~~
This fix uses chrono::nanoseconds in AutomationPoint class to avoid precision error when calculating effective time. Also includes a fixEffectiveTimeOverlaps function when processing the vector of AutomationPoints, which forces the …

Ensure correct point ordering

---

.github/workflows/build.yml
CMakePresets.json
vcpkg_triplets/arm64-osx-11_0.cmake

* Use arm64 triplet with minimum macos version 11.0
* Fix UB generation step (subtly broken since #136)
Previously the arm64 build used the default community triplet arm64-osx. At the time this was built the github action runners were on macos 11.0 which is also the specified minimum os version used when building. The action runners have since been updated causing the linker to emit warnings about a potential mismatch between the vckg build dependencies and the plugins/extension. This commit updates the build to use a modified version of the triplet which sets the minimum macos version when building the dependencies to 11.0 to match the main build.
The UB stage has been broken since artifact tar-ing was added to preserve
permissions on the project upgrade app, this fixes that by adding …

arm64 CI fixes

---

cmake_modules/juce_helpers.cmake
shared/resources/osx/VST-Info.plist.in
tools/project_upgrade/CMakeLists.txt

Only allow valid characters in plugin bundle IDs as specified in
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier
Give upgrade app a bundle ID so it can be notarized
Add NSHumanReadableCopyright key

Update bundle identifiers

---

ear-production-suite-plugins/plugins/scene/src/scene_frontend_connector.cpp

When running a debug build, the assertion in [`SceneBackend::getSelectedProgramme` ](https://github.com/ebu/ear-production-suite/blob/fix_prog_remove_assertion/ear-production-suite-plugins/lib/src/scene_backend.cpp#L170-L180)
would fail if there were 2 or more programmes and the right-most programme was removed. This happens after [`JuceSceneFrontendConnector::removeProgramme`](https://github.com/ebu/ear-production-suite/blob/9d61a7f28dafbb53ae2c768042feb502f3a7aef3/ear-production-suite-plugins/plugins/scene/src/scene_frontend_connector.cpp#L567-L576) is called.
The failure is becuase the programme is removed from the store, but the selected index is not updated and goes out of bounds.
I think the value of selected programme gets updated later (possibly via …

Prevent debug assertion firing during programme removal

---

.gitmodules
ear-production-suite-plugins/lib/src/programme_store_adm_serializer.cpp
reaper-adm-extension/test/reaper_adm/blockbuilders.cpp

Avoids any libadm changes specific for the EPS by implementing the helper function in our own code (it's only used from one place anyway).
One other minor fix was required due to changes in libadm main (`AudioBlockFormatObjects` constructor requires a `SphericalPosition` or `CartesianPosition` object)

Checkout libadm master and provide fixes

---

ear-production-suite-plugins/lib/include/binaural_monitoring_backend.hpp
ear-production-suite-plugins/lib/include/monitoring_backend.hpp
ear-production-suite-plugins/lib/include/scene_backend.hpp
ear-production-suite-plugins/lib/messages/scene_store.proto
ear-production-suite-plugins/lib/src/binaural_monitoring_backend.cpp
ear-production-suite-plugins/lib/src/monitoring_backend.cpp
ear-production-suite-plugins/lib/src/scene_backend.cpp
ear-production-suite-plugins/plugins/binaural_monitoring/src/binaural_monitoring_plugin_processor.cpp
ear-production-suite-plugins/plugins/monitoring/src/monitoring_plugin_processor.cpp
ear-production-suite-plugins/plugins/scene/src/scene_plugin_processor.cpp
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.cpp
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.h

Export was very slow with the binaural plugin. 
#83 has been open for a while which advised disabling monitoring plugins to squeeze more export performance and this is even more relevant now with the heavy load of the bin mon plugin. It also advised on ways to make the waveform display during rendering more relevant. This PR fixes both issues in a slightly different way:
- Scene knows when it is exporting due to connection to extension. It passes this state in monitoring metadata. 
- It does not bother sending any more metadata until exporting is finished (no point - mon plugins don't need it)
- Monitoring backends (both LS and Bin) read and store this state.
- Monitoring AudioProcessors refer to that state to determine what to do during processBlocks:
- If not exporting, method runs as …

Export speed-up and render dialog improvements

---

ear-production-suite-plugins/plugins/scene/src/scene_plugin_processor.cpp
reaper-adm-export-source-plugin/src/PluginProcessor.cpp
reaper-adm-export-source-plugin/src/PluginProcessor.h
reaper-adm-extension/src/reaper_adm/exportaction.cpp
reaper-adm-extension/src/reaper_adm/exportaction.h
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.cpp
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.h
reaper-adm-extension/src/reaper_adm/pluginmain.cpp
reaper-adm-extension/src/reaper_adm/reaperhost.cpp
reaper-adm-extension/src/reaper_adm/reaperhost.h
shared/helper/nng_wrappers.h

This PR combines the comms-fixes and render-dialog-fixes branches (latter is based off the former)
**Problem**: Hang on OSX when trying to render after instantiating either an ADM Export Source or EAR Scene plugin after another EAR Scene.
**Issue**: It seems that an `nng_listen` on POSIX systems for a REQ-REP connection will return an `NNG_EADDRINUSE` if the address is being used (as expected) but in the process it disrupts the connection already on there. No messages are delivered on that connection anymore and they don't even time out - just hang.
**Fix**: For posix since it's all based around the filesystem, we can just do a `stat` to see if the address is in use without disturbing it.
**Sub-problem**: "Command" addresses are not being reused once released. 
**Issue**: Sockets not …

Export Comms and Render Dialog fixes

---

reaper-adm-extension/src/reaper_adm/admmetadata.cpp

The conversion function must remove the existing ACF reference from the ATU before adding a AT ref, otherwise libadm throws.

Fix conversion to 2076-1 on import

---

.gitmodules
reaper-adm-extension/src/reaper_adm/pcmwriter.cpp

Creating a project from an ADM BW64 which contains large assets (>4gb when extracted) would fail to reimport those assets due to REAPER not recognising the BW64 chunk ID. RF64 is supported and since we are not using the additional chunks of BW64 in this process, it is perfectly acceptable to use the RF64 ID.
Note that this fix involves using a custom fork of libbw64 in order to force use of RF64.

Force use of RF64 ID on assets to be reimported

---

ear-production-suite-plugins/lib/CMakeLists.txt
ear-production-suite-plugins/lib/include/ui/direct_speakers_frontend_backend_connector.hpp
ear-production-suite-plugins/lib/include/ui/hoa_frontend_backend_connector.hpp
ear-production-suite-plugins/lib/include/ui/object_frontend_backend_connector.hpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_component.hpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_frontend_connector.cpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_frontend_connector.hpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_plugin_editor.cpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_plugin_processor.cpp
ear-production-suite-plugins/plugins/direct_speakers/src/direct_speakers_plugin_processor.hpp
ear-production-suite-plugins/plugins/direct_speakers/src/value_box_main.hpp
ear-production-suite-plugins/plugins/hoa/src/hoa_component.hpp
ear-production-suite-plugins/plugins/hoa/src/hoa_frontend_connector.cpp
ear-production-suite-plugins/plugins/hoa/src/hoa_frontend_connector.hpp
ear-production-suite-plugins/plugins/hoa/src/hoa_plugin_editor.cpp
ear-production-suite-plugins/plugins/hoa/src/hoa_plugin_processor.cpp
ear-production-suite-plugins/plugins/hoa/src/hoa_plugin_processor.hpp
ear-production-suite-plugins/plugins/hoa/src/value_box_main.hpp
ear-production-suite-plugins/plugins/object/src/object_component.hpp
ear-production-suite-plugins/plugins/object/src/object_frontend_connector.cpp
ear-production-suite-plugins/plugins/object/src/object_frontend_connector.hpp
ear-production-suite-plugins/plugins/object/src/object_plugin_editor.cpp
ear-production-suite-plugins/plugins/object/src/object_plugin_processor.cpp
ear-production-suite-plugins/plugins/object/src/object_plugin_processor.hpp
ear-production-suite-plugins/plugins/object/src/value_box_main.hpp
shared/components/ear_name_text_editor.hpp

Checkbox implemented - will enable/disable editing of name editor
State held in frontend connector. Messaging to scene is working. Save/load of state is working.

Custom AudioObject names

---

ear-production-suite-plugins/lib/include/scene_gains_calculator.hpp
ear-production-suite-plugins/lib/include/scene_store.hpp
ear-production-suite-plugins/lib/src/scene_gains_calculator.cpp
ear-production-suite-plugins/lib/src/scene_store.cpp

**Original issue;**
The `SceneGainsCalculator` class just kept a single pair of gains tables (vector of vectors, one for diffuse and one for direct feeds) for all items (i.e, AudioObjects).  
The `SceneGainsCalculator::update` method would iterate through all items in the store and run the `addOrUpdateItem` method to set the gains for the item in the gains tables (`direct_` and `diffuse_` members). Likewise the `removeItem` method would zero affected entries in the tables. Due to this "overwrite" behaviour, it meant that input sharing between objects was not possible. The last item to be processed in the store would overwrite gains set by any previous item which is also using those input channels.
**Solution:**
Each item keeps it's own pair of gains tables in the existing `ItemRouting` …

Fix monitoring for objects sharing input audio 

---

ear-production-suite-plugins/plugins/binaural_monitoring/src/binaural_monitoring_plugin_processor.cpp
ear-production-suite-plugins/plugins/binaural_monitoring/src/binaural_monitoring_plugin_processor.hpp
ear-production-suite-plugins/plugins/monitoring/src/monitoring_plugin_processor.cpp
ear-production-suite-plugins/plugins/monitoring/src/monitoring_plugin_processor.hpp
ear-production-suite-plugins/plugins/scene/src/scene_plugin_processor.cpp
ear-production-suite-plugins/plugins/scene/src/scene_plugin_processor.hpp
reaper-adm-export-source-plugin/src/CMakeLists.txt
reaper-adm-export-source-plugin/src/PluginProcessor.cpp
reaper-adm-export-source-plugin/src/PluginProcessor.h

Setting `BusesProperties` in a `AudioProcessor` ctor sets the default layout for the plugin.
If this is 128 channels, REAPER v6.x will still instantiate the plugin and appear happy with it, but never call the `processBlock` method, so level monitoring, export and DSP will not run.
Therefore, it is necessary to know if we are running under REAPER with a 64 channel limitation within the plugins. The extension already provided an exposed function to do this, which could be called via the `DetermineChannelCount` helper. A handle to the host is grabbed via `setIHostApplication` - however, this is only called AFTER the plugin has been constructed, when we would need to set the default layout.
A bus can be resized at any time using the JUCE `setChannelLayoutOfBus` function. However, this always …

Fix backwards compatibility with 64ch REAPER versions

---

reaper-adm-extension/src/reaper_adm/exportaction_admsourcescontainer.cpp
reaper-adm-extension/src/reaper_adm/plugin_deprecation_warning.h
reaper-adm-extension/src/reaper_adm/pluginmain.cpp

Warns user that support for third-party plugin suites will be dropped in future versions. Message is shown when the user imports ADM using a third-party plugin suite in to a new project or in to an existing project. Warning also shows in the render dialog when "ADM" output format is selected and instances of the ADM Export Source VST are found.
This has been mainly implemented in it's own header so we can easily strip it out and make sure we don't leave anything behind (compiler will point out all the affected bits of code once the header is deleted).

Third-Party Plugin Support Deprecation Warning

---

ear-production-suite-plugins/lib/include/binaural_monitoring_backend.hpp
ear-production-suite-plugins/lib/include/communication/monitoring_metadata_receiver.hpp
ear-production-suite-plugins/lib/include/monitoring_backend.hpp
ear-production-suite-plugins/lib/include/scene_gains_calculator.hpp
ear-production-suite-plugins/lib/src/binaural_monitoring_backend.cpp
ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp
ear-production-suite-plugins/lib/src/monitoring_backend.cpp
ear-production-suite-plugins/lib/src/scene_gains_calculator.cpp

As per #277, a crash would occur (probably only on windows) if the `AdmPresetDefinitionsHandler` was first instantiated as a singleton via an NNG message, due to the NNG threads having a small stack. We had previously overcome a similar issue in the LS monitoring plugins by wrapping `SceneGainsCalculator::update` code in a thread. I used a similar fix here, but it made sense for the thread launching to occur further up the call stack since for both the LS mons and Bin mon, the message handler call stems from `MonitoringMetadataReceiver::handleReceive`
LS mon call stack from message received to `SceneGainsCalculator::update` where a new thread would be launched:
```
EAR Monitoring 9+10+3.vst3!ear::plugin::SceneGainsCalculator::update(ear::plugin::proto::SceneStore store) Line 56
EAR …
```

Fix #277 - Stack overflow in Bin Mon message handler

---

CHANGELOG.md
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.cpp
reaper-adm-extension/src/reaper_adm/exportaction_dialogcontrol.h

Having normalisation enabled during render will cause render to fail, since it does a multiple pass.
The fix currently implemented for v1.2 does not actually disable Normalisation if it was previously enabled. It seems that unchecking the normalisation checkbox (in later versions of REAPER ~v7.34) does not actually stop normalisation happening. We only seem to set the visual appearance of the checkbox. We must simulate a click to fire any listeners attached to the checkbox.
We still need a solution for previous versions of REAPER which do not have this checkbox. Normalisation is configured in a separate window, so we can't realistically control that. The best solution is probably just to show an error that render will fail due to normalisation being enabled.

Workaround normalisation enabled during render

---

vcpkg.json

This release of vcpkg fixes a bug where newer releases of VS 2022 (17.10+) weren't being detected ("error: in triplet x64-windows-static: unable to find a valid Visual Studio instance")
However bumping vcpkg version also means boost 1.84 rather than 1.83 was used. Something has changed between these two versions where boost-rational is no longer pulled down automatically (presumably it used to come down as part of boost-math). That is fixed by explicitly stating in vcpkg.json.

Update vcpkg to 2024.02.14
